DEBUG = True
SECRET_KEY = 'GALACAT_SECRET_KEY'

SQLALCHEMY_TRACK_MODIFICATIONS = False
PSYCOPG_DEBUG=1

UPLOAD_FOLDER = 'media'
NUM_PAGE = 20

SQLALCHEMY_DATABASE_URI = ''
UPLOAD_FOLDER = '/path/to/media'
